version: "3.7"

services:
  ehrlichgpt:
    build: .
    image: ehrlichgpt
    container_name: ehrlichgpt
    restart: unless-stopped
    volumes:
      - "./conversations/:/app/conversations/"
    environment:
      - OPENAI_API_KEY
      - DISCORD_BOT_TOKEN
      - BING_SUBSCRIPTION_KEY
      - CHROME_DRIVER_PATH
      - BING_SEARCH_URL=https://api.bing.microsoft.com/
